### ISSUE TITLE
Exceptions Thrown by Rider EAP

### ISSUE THREAD

**Issue by djsipe** [mallowigi/material-theme-jetbrains#17]
Hi there.  This theme works great in the other JetBrains products.  I use it in PHPStorm and DataGrip w/o any issue.  However in the EAP of Rider, I'm getting the following error:

```
com/intellij/psi/JavaDirectoryService
java.lang.NoClassDefFoundError: com/intellij/psi/JavaDirectoryService
	at com.chrisrm.idea.icons.MTFileIconProvider.getDirectoryIcon(MTFileIconProvider.java:80)
	at com.chrisrm.idea.icons.MTFileIconProvider.getIcon(MTFileIconProvider.java:45)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:118)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:59)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
	at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:161)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:161)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:147)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:145)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:160)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.JavaDirectoryService PluginClassLoader[com.chrisrm.idea.MaterialThemeUIFork, 0.3.4.2]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more
```

My hunch is it's just a symptom of Rider being a bit unstable, but it might be something more... not sure.  Let me know if there's any more info you need.  That's about all I could find.

I'm using:

> Rider 1.0 EAP
> Build #RS-171.4089.466, built on April 27, 2017
> Rider EAP User
> Expiration date: May 27, 2017
> JRE: 1.8.0_112-release-736-b16 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Mac OS X 10.12.4

**Comment by mallowigi** [comment]
I tried to play a bit with Rider and I dont' get what you are getting. What type of project are you using? I tried with ASP.NET, Console Application and Empty Project

**Comment by mallowigi** [comment]
Oh wait never mind there it is.

**Comment by mallowigi** [comment]
Ok should be fixed in the latest release

**Comment by djsipe** [comment]
Thanks!  Sorry github email landed in Spam.  Will check it out.

**Comment by djsipe** [comment]
Looks good!  Thanks!
